# Generated by Django 3.2.4 on 2021-08-17 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
