# Generated by Django 3.2.4 on 2021-06-27 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings_bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=150, verbose_name='Токен')),
                ('tg_chat', models.CharField(max_length=150, verbose_name='ID')),
                ('tg_message', models.CharField(max_length=150, verbose_name='Сообщение')),
            ],
        ),
    ]
