# Generated by Django 3.2.4 on 2021-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings_bot',
            name='tg_message',
            field=models.TextField(verbose_name='Сообщение'),
        ),
    ]
